name: Contract Release

on:
  push:
    tags:
      - 'v*'
      
permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  release-contract:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'Release of the DAO contract'
      home_domain: 'reflector.network'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}